### ISSUE TITLE
Support default page for not found requests (good for Angular).

### ISSUE THREAD

**Issue by kilork** [kilork/actix-web-static-files#11]

**Comment by Heiss** [comment]
Hey,

any progress on this? I would like to use this crate for a single page app.

**Comment by kilork** [comment]
@Heiss What is why we have this issue tracker, I see someone interested in this feature and would implement it sooner. Thanks for your interest!

**Comment by Heiss** [comment]
Thank you for your power. :) I am a very beginner with rust and maybe cannot help you alot, but if you have a starting point for me to contribute, please let me know.

I want to use your crate to build a cloud-native backend api server for my single page app. Maybe it helps to understand the context for my usage. :)

**Comment by kilork** [comment]
I am building now a kind of minimal angular app to show off a mvp. I will report my progress here, seems like somehow it involves more small steps...

**Comment by kilork** [comment]
I will follow this tutorial: https://angular.io/guide/router-tutorial
