### ISSUE TITLE
no default features for actix-web

### ISSUE THREAD

**Issue by robjtede** [kilork/actix-web-static-files#16]
The dependency in Cargo.toml should ideally be:

```diff
- actix-web = "3.0.2"
+ actix-web = { version = "3.0.2", default-features = false }
```

**Comment by kilork** [comment]
Thank you for your feedback!

How do you think, should we release it just as 3.0.x or 3.1.x?

**Comment by robjtede** [comment]
Up to you but patch release is fine. This isn't breaking in any way.

**Comment by kilork** [comment]
Ok, one more time thanks for suggestion. Just released https://github.com/kilork/actix-web-static-files/releases/tag/v3.0.1 with those changes.
