### ISSUE TITLE
implementation Clone for Resource

### ISSUE THREAD

**Issue by ctaque** [kilork/actix-web-static-files#22]
Resource does not implement Clone so I cannot generate the file list before running the server.
I do need this because my server is behind a command, not directly in the main : 

```rust
      // main.rs

       include!(concat!(env!("OUT_DIR"), "/generated.rs"));

       async fn main() -> std::io::Result<()> {
               let generated_static_files_list = generate();
                 Cmd::Listen { address, port } => {
                           Command::listen(generated_static_files_list).await
                 }
        }

      // cli.rs
       fn listen(generated: HashMap<&'static str, Resource>)
            HttpServer::new(move || { // the trait std::clone::Clone is not implemented for actix_web_static_files::Resource
            App::new()
                .service(actix_web_static_files::ResourceFiles::new(
                    "/static",
                    generated
                )) 
                ...
        }
```

**Comment by kilork** [comment]
I know about this problem, but actually that I am thinking of is to allow share this immutable data across `Send` (most obviosly with `Arc`). Why it is not perfect to `Clone`? This will make transparent and easy to do this, and many people can just use it without knowledge, that it has as side effect.

`actix-web` starts worker for each available core on machine, this means it creates on modern server about 16 copies and on my pretty weak mac it is still 4 copies. For huge apps this means real waste of memory.

So let's keep this for a little bit and check other options we have.

**Comment by kilork** [comment]
Consider this as an alternative to Arc: https://github.com/bodil/im-rs.
