### ISSUE TITLE
Help on getting the examples to run

### ISSUE THREAD

**Issue by theSage21** [kilork/actix-web-static-files#46]
Hi,

I'm learning Rust and throughly enjoying the process. Thanks a lot for building such a great crate !

I've been stuck on this error for a few days now and am unable to figure out what the correct way to resolve it is.
I'm trying to build a very simple application 

```
error[E0308]: mismatched types
  --> src/main.rs:26:61
   |
26 |                     .service(ResourceFiles::new("/static/", generated))
   |                                                             ^^^^^^^^^ expected struct `actix_web_static_files::Resource`, found struct `static_files::Resource`
   |
   = note: expected struct `std::collections::HashMap<&'static str, actix_web_static_files::Resource>`
              found struct `std::collections::HashMap<&str, static_files::Resource>`

For more information about this error, try `rustc --explain E0308`.
```

The application code is also fairly simple:

```
use actix_web::{App, HttpServer};
mod constants;
mod db;
mod license;
mod staticfiles;
use actix_web_static_files::ResourceFiles;

include!(concat!(env!("OUT_DIR"), "/generated.rs"));

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    match db::ensure_migrations() {
        true => {
            println!("Migrations sync complete.");
            HttpServer::new(|| {
                let generated = generate();
                App::new()
                    .data(license::LicenseState {
                        is_valid: license::get_license_state(),
                    })
                    .service(license::index)
                    .service(license::get_license)
                    .service(license::post_license)
                    .service(staticfiles::js_file_server)
                    .service(staticfiles::css_file_server)
                    .service(ResourceFiles::new("/static/", generated))
            })
            .workers(1)
            .bind("127.0.0.1:8080")?
            .run()
            .await
        }
        false => {
            println!("Unable to complete migrations. Shutting down.");
            Ok(())
        }
    }
}
```

If anyone  can point me in the right direction about what I should be reading about/ investigating that would be enough.

**Comment by kilork** [comment]
Hi!

Can you show your `Cargo.toml`? Seems like you have dependencies in build and dev parts for different incompatible versions.

**Comment by theSage21** [comment]
I'm following instructions from the Readme of the project.

Here's a fully reproducible example asking with the Cargo.toml

https://github.com/thesage21/example

**Comment by kilork** [comment]
Yeap, this is master version, it was not released yet. Last released version is `3.0.5`. You can read documentation using tag link: https://github.com/kilork/actix-web-static-files/tree/v3.0.5

Or you can find stable version on crates: https://crates.io/crates/actix-web-static-files

Here are examples for `v3.0`: https://github.com/kilork/actix-web-static-files-examples/tree/v3.0

(there is actually only `webpack` example, but it is basically the same in terms of deps and basic structure)

`v3.1` is not released at the moment, so using it possible, but only if you use git dependencies. I would not recommend it for now, because it is breaking change version.

**Comment by theSage21** [comment]
Okay.

I think I'll just use the master version since the instructions for master
and 3.0.x are essentially the same and are causing errors for me.

Thanks 😊

**Comment by kilork** [comment]
You are welcome!

I've added a note to readme, sorry for confusing information!
